"""
Markdown Formatter for Search Results
"""

import os
from pathlib import Path
from typing import List, Dict, Any
from datetime import datetime


class MarkdownFormatter:
    """Format search results and page content as markdown"""

    @staticmethod
    def format_search_results(
        query: str, results: List[Dict[str, Any]], engine: str
    ) -> str:
        """Format search results as markdown"""
        md = f"# Search Results: {query}\n\n"
        md += f"**Search Engine:** {engine}\n"
        md += f"**Date:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n"
        md += f"**Total Results:** {len(results)}\n\n"
        md += "---\n\n"

        for idx, result in enumerate(results, 1):
            md += f"## {idx}. {result.get('title', 'No Title')}\n\n"
            md += f"**URL:** [{result.get('url', '')}]({result.get('url', '')})\n\n"

            if result.get("snippet"):
                md += f"**Snippet:**\n{result.get('snippet')}\n\n"

            md += "---\n\n"

        return md

    @staticmethod
    def format_page_content(
        url: str,
        metadata: Dict[str, str],
        content: str,
        tables: List[str] = None,
        screenshot_path: str = None,
    ) -> str:
        """Format scraped page content as markdown"""
        md = f"# {metadata.get('title', 'Untitled')}\n\n"
        md += f"**URL:** {url}\n\n"

        if metadata.get("description"):
            md += f"**Description:** {metadata['description']}\n\n"

        if metadata.get("author"):
            md += f"**Author:** {metadata['author']}\n\n"

        if metadata.get("date"):
            md += f"**Date:** {metadata['date']}\n\n"

        if metadata.get("keywords"):
            md += f"**Keywords:** {metadata.get('keywords')}\n\n"

        if screenshot_path:
            md += f"**Screenshot:** `{screenshot_path}`\n\n"

        md += "---\n\n"
        md += "## Content\n\n"
        md += content

        # Add tables if found
        if tables:
            md += "\n\n---\n\n"
            md += "## Tables\n\n"
            for table in tables:
                md += table + "\n"

        return md

    @staticmethod
    def format_summary(
        query: str,
        search_results: List[Dict[str, Any]],
        scraped_pages: List[Dict[str, Any]],
        engine: str,
    ) -> str:
        """Format a summary of the scraping session"""
        md = f"# Scraping Summary: {query}\n\n"
        md += f"**Search Engine:** {engine}\n"
        md += f"**Date:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n"
        md += f"**Search Results Found:** {len(search_results)}\n"
        md += f"**Pages Scraped:** {len(scraped_pages)}\n\n"
        md += "---\n\n"

        md += "## Search Results\n\n"
        for idx, result in enumerate(search_results, 1):
            md += (
                f"{idx}. [{result.get('title', 'No Title')}]({result.get('url', '')})\n"
            )

        md += "\n## Scraped Pages\n\n"
        for idx, page in enumerate(scraped_pages, 1):
            md += f"{idx}. [{page.get('title', 'No Title')}]({page.get('url', '')})\n"
            if page.get("screenshot"):
                md += f"   - Screenshot: `{page.get('screenshot')}`\n"
            if page.get("markdown_file"):
                md += f"   - Markdown: `{page.get('markdown_file')}`\n"

        md += "\n---\n\n"
        md += f"*Generated by Web Search Scraper v1.0.0*\n"

        return md

    @staticmethod
    def save_markdown(content: str, filepath: str) -> bool:
        """Save markdown content to file"""
        try:
            Path(filepath).parent.mkdir(parents=True, exist_ok=True)
            with open(filepath, "w", encoding="utf-8") as f:
                f.write(content)
            return True
        except Exception as e:
            print(f"Error saving markdown: {e}")
            return False
